// #include <stdio.h>
// #include <vector>
// #include <string>

// // 1. Bullet Caching
// extern "C" int b3IsFileCachingEnabled() {
//     return 0;
// }

// // 2. STB Image - Force C Linkage and specific names
// extern "C" {
//     #define STB_IMAGE_IMPLEMENTATION
//     #include "ThirdPartyLibs/stb_image/stb_image.h"

//     #define STB_IMAGE_WRITE_IMPLEMENTATION
//     #include "ThirdPartyLibs/stb_image/stb_image_write.h"
    
//     // Explicit bridge just in case the define didn't expose it correctly
//     unsigned char *stbi_load_from_memory(unsigned char const *buffer, int len, int *x, int *y, int *channels_in_file, int desired_channels) {
//         return stbi_load_from_memory(buffer, len, x, y, channels_in_file, desired_channels);
//     }
// }

// // // 3. TinyOBJ - Force the exact signature Bullet wants
// // #define TINYOBJLOADER_IMPLEMENTATION
// // #include "ThirdPartyLibs/Wavefront/tiny_obj_loader.h"

// // namespace bt_tinyobj {
// //     // We use std::string because your previous error log noted 
// //     // the old declaration returned std::string
// //     std::string LoadObj(attrib_t& attrib, std::vector<shape_t>& shapes, const char* filename, const char* mtl_basedir, CommonFileIOInterface* fileIO) {
// //         std::string err;
// //         // Call the implementation generated by the header
// //         // We use the full namespace to avoid recursion
// //         bt_tinyobj::LoadObj(attrib, shapes, filename, mtl_basedir, fileIO); 
// //         return err;
// //     }
// // }

// #define TINYOBJLOADER_IMPLEMENTATION
// #include "ThirdPartyLibs/Wavefront/tiny_obj_loader.h"

// namespace bt_tinyobj {
//     std::string LoadObj(attrib_t& attrib, std::vector<shape_t>& shapes, std::vector<material_t>& materials, const char* filename, const char* mtl_basedir, CommonFileIOInterface* fileIO) {
//         // Redirect to the actual tinyobjloader function
//         // Ensure the parameters match what the header actually provides
//         bool ret = tinyobj::LoadObj(&attrib, &shapes, &materials, filename, mtl_basedir);
//         return ret ? "" : "Failed to load OBJ";
//     }
// }



// // 1. Bullet Caching
// extern "C" int b3IsFileCachingEnabled() {
//     return 0;
// }

// // 2. STB Image - Force External Visibility
// extern "C" {
//     // These macros tell STB "Don't make these functions static"
//     #define STBIDEF extern
//     #define STBIWDEF extern
    
//     #define STB_IMAGE_IMPLEMENTATION
//     #include "ThirdPartyLibs/stb_image/stb_image.h"

//     #define STB_IMAGE_WRITE_IMPLEMENTATION
//     #include "ThirdPartyLibs/stb_image/stb_image_write.h"
// }

// // 3. TinyOBJ - Remains the same
// #define TINYOBJLOADER_IMPLEMENTATION
// #include "ThirdPartyLibs/Wavefront/tiny_obj_loader.h"

// namespace bt_tinyobj {
//     std::string LoadObj(
//         attrib_t& attrib,
//         std::vector<shape_t>& shapes,
//         const char* filename,
//         const char* mtl_basepath,
//         CommonFileIOInterface* fileIO) 
//     {
//         return ::bt_tinyobj::LoadObj(attrib, shapes, filename, mtl_basepath, fileIO);
//     }
// }


#include <stdio.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

// This is the only thing the core Bullet libraries still demand
extern "C" int b3IsFileCachingEnabled() { 
    return 0; 
}